export enum ServiceID {
    all = 'all',
    marketResearch = 'market-research',
    marketInsight = 'market-insight',
    brandDesign = 'brand-design',
    webDesign = 'web-design',
    mediaStrategy = 'media-strategy',
    contentCreation = 'content-creation',
    webDevelopment = 'web-development',
    customEmail = 'custom-email',
    reputationManagement = 'reputation-management',
    omnichannelRetailing = 'omnichannel-retailing',
    abandonmentReduction = 'abandonment-reduction',
    brandAwareness = 'brand-awareness',
    salesGeneration = 'sales-generation',
    leadGeneration = 'lead-generation',
    trafficGeneration = 'traffic-generation',
    customerEducation = 'customer-education',
    marketCare = 'market-care',
    webCare = 'web-care',
}